# The vilan toolchain — generated by scripts/brew-formula.sh in
# https://github.com/vilan-lang/vilan and pushed here by that repository's
# release workflow. Edit the script, never this file.
class Vilan < Formula
  desc "Language toolchain for vilan: the compiler and the language server"
  homepage "https://vilan-lang.org/docs/"
  version "0.29.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.29.0/vilan-aarch64-apple-darwin.tar.gz"
      sha256 "c8b5f45252f94cc4c0c0387dfe8c61ea11091d2ea7346c4eb3c56e76d7a78ed1"
    end

    on_intel do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.29.0/vilan-x86_64-apple-darwin.tar.gz"
      sha256 "fbd0a2ac416d189b7e1242705bdea67e82431e70465fb2cbccc806c6aa6ed011"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.29.0/vilan-aarch64-unknown-linux-musl.tar.gz"
      sha256 "396a5f320ef3f25e78fb1876696fc2f35e960ebb0962343e51eb3e87ea484208"
    end

    on_intel do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.29.0/vilan-x86_64-unknown-linux-musl.tar.gz"
      sha256 "d9cb62b6fbc333056f4181d2e18af1848d6393e18f198ba1b0634b81375e0d63"
    end
  end

  def install
    bin.install "vilan", "vilan-lsp"
    # Both licenses travel with the binaries they cover: the archive carries
    # them, and redistributing under either one means shipping its text. The
    # third-party notices cover the statically linked crates the same way.
    prefix.install "LICENSE-MIT", "LICENSE-APACHE"
    prefix.install "THIRD-PARTY-NOTICES.txt" if File.exist?("THIRD-PARTY-NOTICES.txt")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vilan --version")
  end
end
