# The vilan toolchain — generated by scripts/brew-formula.sh in
# https://github.com/vilan-lang/vilan. Edit the script, never this file. The
# live tap (vilan-lang/homebrew-vilan) is regenerated by release.yml's
# publish-brew job on every release; a copy staged at
# homebrew/Formula/vilan.rb in the vilan repo itself is a pinned seed fixture
# for crates/vilan-cli/tests/brew_formula.rs's byte-identical test, not a
# mirror of the current release.
class Vilan < Formula
  desc "Language toolchain for vilan: the compiler and the language server"
  homepage "https://vilan-lang.org/docs/"
  version "0.39.0"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.39.0/vilan-aarch64-apple-darwin.tar.gz"
      sha256 "15a68a10c050983f82b545cd8088ba38d66056e48e82cd8e8db34ec6356f714f"
    end

    on_intel do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.39.0/vilan-x86_64-apple-darwin.tar.gz"
      sha256 "317bbd578509e2cb2886b7fd5965c26f30550120933f7dab05a7a7e2d0d411a9"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.39.0/vilan-aarch64-unknown-linux-musl.tar.gz"
      sha256 "905d19f2651dafc90347f1d13e14564a2669f08a556d9fb7435e1eeddad84cf9"
    end

    on_intel do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.39.0/vilan-x86_64-unknown-linux-musl.tar.gz"
      sha256 "dda1e84d25471b699ca5859040d99cada4aeb3382fbd1dfe489377d73a1e0a6e"
    end
  end

  def install
    bin.install "vilan", "vilan-lsp"
    # Both licenses travel with the binaries they cover: the archive carries
    # them, and redistributing under either one means shipping its text. The
    # third-party notices cover the statically linked crates the same way.
    prefix.install "LICENSE-MIT", "LICENSE-APACHE"
    prefix.install "THIRD-PARTY-NOTICES.txt" if File.exist?("THIRD-PARTY-NOTICES.txt")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vilan --version")
  end
end
