# The vilan toolchain — generated by scripts/brew-formula.sh in
# https://github.com/vilan-lang/vilan and pushed here by that repository's
# release workflow. Edit the script, never this file.
class Vilan < Formula
  desc "Language toolchain for vilan: the compiler and the language server"
  homepage "https://vilan-lang.org/docs/"
  version "0.22.1"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.22.1/vilan-aarch64-apple-darwin.tar.gz"
      sha256 "f7db08ee3da74befccb13334193b45c411c544a76a4f314de245dc3483f42ba8"
    end

    on_intel do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.22.1/vilan-x86_64-apple-darwin.tar.gz"
      sha256 "6271f263b07b9d7bc5e0dfd10038e8f9db10c88d67d518961ca380da74c3169b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.22.1/vilan-aarch64-unknown-linux-musl.tar.gz"
      sha256 "516ef7a33c0ccce53aaba70d9f11e8ed1c8f1825b35890a0dcbd9206c9b2c822"
    end

    on_intel do
      url "https://github.com/vilan-lang/vilan/releases/download/v0.22.1/vilan-x86_64-unknown-linux-musl.tar.gz"
      sha256 "3795336ece9ad7a7ab3d433cc8376fd4a6aad3ac32391b551ef636b8a5d31d41"
    end
  end

  def install
    bin.install "vilan", "vilan-lsp"
    # Both licenses travel with the binaries they cover: the archive carries
    # them, and redistributing under either one means shipping its text. The
    # third-party notices cover the statically linked crates the same way.
    prefix.install "LICENSE-MIT", "LICENSE-APACHE"
    prefix.install "THIRD-PARTY-NOTICES.txt" if File.exist?("THIRD-PARTY-NOTICES.txt")
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/vilan --version")
  end
end
